language: node_js
version: "10"
before_install:
  - nosudo apt-get install -y build-essential python
script: cd course-03/udacity-c3-restapi-user && npm install && ../udacity-c3-restapi-feed && npm install && ../udacity-c3-frontend && npm install